### PR TITLE
Support Erlang 20 AtU8 beam chunk

### PR DESCRIPTION
**Pull request by tomas-abrahamsson**
With Erlang 20, there's a new AtU8 chunk. This commit adds support for it, while still supporting the Atom chunk. I tested with commit [ffa80a4](https://github.com/erlang/otp/commit/ffa80a41370025ed2fb95967e731f13cc7e45e4f) on master, to be Erlang 20, and Erlang 19.2.1. Judging by the [beam_lib](https://github.com/erlang/otp/blob/ffa80a41370025ed2fb95967e731f13cc7e45e4f/lib/stdlib/src/beam_lib.erl#L793-L817), the format of the atoms in the AtU8 chunk is the same as of the Atom chunk, only the actual encoding differs.

### CODE REVIEW

**Comment by tomas-abrahamsson** [comment]
Side note: there are also a few other Erlang 20 issues that this PR does not address:
```
===> Compiling mockgyver
src/mockgyver.erl:408: Warning: gen_fsm:start_link/4 is deprecated and will be removed in a future release; use gen_statem:start/4
src/mockgyver.erl:820: Warning: gen_fsm:sync_send_event/3 is deprecated and will be removed in a future release; use gen_statem:call/3
src/mockgyver.erl:823: Warning: gen_fsm:sync_send_all_state_event/3 is deprecated and will be removed in a future release; use gen_statem:call/3

_build/test/lib/mockgyver/test/mockgyver_tests.erl:40: Warning: export_all flag enabled - all functions will be exported
```

**Comment by tomas-abrahamsson** [comment]
I just updated the branch with a fixup-type commit: to use the proper encoding when storing the new atom name, instead of always latin1. As far as Erlang 20 is concerned, it appears module names are still always latin1 (see erlang/otp#1378), but might matter for some later Erlang version.

I suppose I should squash the changes? Just wanted to let you know what's changed first.

**Comment by klajo** [comment]
Thanks! Squashing sounds good.

Also, thanks for the heads-up on the other compiler warnings.  How would one want to treat those?  gen_statem is not available in 18 and earlier.  Deprecation warnings are shown in 20 and later.  Switch to plain_fsm to support a wider range of versions?  Any ideas?

**Comment by tomas-abrahamsson** [comment]
Squashed!

I don't really know a good path to go for eliminating warnings. On the note of switching to plain_fsm, maybe ordinary spawn and receive would even be good enough considering the scope of use in unit testing. It might also be possible to do some ifdef trickery with the preprocessor. Don't know how feasible that would be. I suppose it means turning rebar.config into rebar.config.script.

(I was going to suggest that the introduction of the OTP_RELEASE macro, as described in [eep-0044](http://erlang.org/eeps/eep-0044.md), would coincide nicely with testing for presence of gen_statem, but unfortunately, it seems it actually never made it into the release, so to say. So rebar.config would still need to be .script-ified if going for ifdefs/macros).

**Comment by klajo** [comment]
Good point with an ordinary spawn/receive.  I thing I prefer that (or the plain_fsm) route over some ifdef solution to keep the code cleaner.

Thanks for the contribution!

**Comment by tomas-abrahamsson** [comment]
Super!

**Pull request merged**
