### PR TITLE
Resume after cleanup when a session has crashed

### PR DESCRIPTION
**Pull request by tomas-abrahamsson**
Recently I was developing (in an interactive shell inside emacs) some unit tests where the process under test gets linked to the test process, and the process under test sometimes crashed. After this, I often had to resort to `application:stop(mockgyver), application:start(mockgyver).`  until I began looking into mockgyver itself to try to debug things. (Initially, I didn't understand what was wrong, and spraying with more and more debug printouts, I eventually got quite perplexed that not even the `setup/0` function was called. This eventually lead me to debugging mockgyver itself).

I think it moves in the right direction because things hanging in a call auto-inserted by a parse transform can be a bit daunting to hunt for :) However, I'm not entirely sure this is the full solution, since I think that at some point I saw mockgyver crash in a function clause, but I couldn't reproduce that. 

The added test has the runs ok, but if one wants to check what happens without the accompanying fix, one typically only experiences that mockgyver hangs (or it just times out), not that the test fails. I tried to come up with a better test, but failed at that.

### CODE REVIEW

**Comment by tomas-abrahamsson** [comment]
Rebased to let travis chew on it

**Comment by klajo** [comment]
Thanks, this looks like a nice and much needed improvement.  It doesn't look right to stay in the same state as the previous version did (and not dequeue any waiters).  One thought though: would it perhaps be a good idea to break out the code into a helper function, since it's more or less the same in the [normal case](https://github.com/klajo/mockgyver/blob/master/src/mockgyver.erl#L548) and the 'DOWN' case?

**Comment by tomas-abrahamsson** [comment]
Good point, I've now refactored it and force-pushed.

**Comment by klajo** [comment]
Travis is happy and so am I, thanks!

**Comment by klajo** [comment]
Included in [mockgyver 1.1.2](https://hex.pm/packages/mockgyver/1.1.2).

**Pull request merged**
